development:
  clients:
    default:
      database: development
      hosts:
        - 127.0.0.1:27021
#        - 127.0.0.1:27022
#        - 127.0.0.1:27023
      options:
#        user: 'admin'
#        password: 'password'

  options:
    duplicate_fields_exception: true

test:
  clients:
    default:
      database: test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
