# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.0.6'

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem 'rails', '~> 7.1.2'

# Use sqlite3 as the database for Active Record
gem 'sqlite3', '~> 1.4'

# Use the Puma web server [https://github.com/puma/puma]
gem 'puma', '>= 5.0'

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "jbuilder"

# Use Redis adapter to run Action Cable in production
# gem "redis", ">= 4.0.1"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mswin mswin64 mingw x64_mingw jruby]

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', require: false

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin Ajax possible
gem "rack-cors"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem 'debug', platforms: %i[mri mswin mswin64 mingw x64_mingw]
end

group :development do
  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end

gem 'better_errors', '~> 2.10'
gem 'mongoid', '~> 8.1'
gem 'redis', '~> 5.0'
gem 'sidekiq', '~> 7.2'
gem 'logging', '~> 2.3'
gem 'faker', '~> 3.2'
gem 'rspec', '~> 3.12'
gem 'rubocop', '~> 1.58'
gem 'rubocop-rails', '~> 2.22'
# gem "redis-semaphore", "~> 0.3.1"
gem 'haml', '~> 5.1.1'
gem 'haml-rails', '~> 2.0.1'
gem 'parallel'
gem 'oj', '~> 3.14'
gem 'marky_markov'
gem 'amazing_print'
gem 'concurrent-ruby', '~> 1', require: 'concurrent'
gem 'httparty', '~> 0.18.1'
gem 'rest-client', '~> 2.0.2'
gem 'bundle-audit'
gem 'hashie'
gem 'active_data', '~> 1.1.4'